import { Component, ViewEncapsulation } from '@angular/core';
import { SortDescriptor, orderBy } from '@progress/kendo-data-query';
import { GridDataResult, PageChangeEvent } from '@progress/kendo-angular-grid';

@Component({
    selector: 'app-root',
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.css'],
    encapsulation: ViewEncapsulation.None
})
export class AppComponent {

    constructor() {
        this.loadProducts();
    }

    public gridData: GridDataResult;
    public pageSize = 10;
    public skip = 0;
    public isShowTooltip =true;
    public searchString = '';
    public columns = [
        { title: 'Resident', field:'Resident', width:100 },
        { title: 'Unit', field:'UnitName' },
        { title: 'Room Bed', field:'RoomBed' },
        { title: 'ADL Date/Time', field:'ADLdtFormatted' },
        { title: 'Bed Mobility', groupTitle: 'Bed Mobility',
        children: [
            {field:'AdlMobility', title:'Self'}, 
            {field:'AdlMobilitySup', title:'Support' }]},
        { title: 'Transfer', groupTitle: 'Transfer',
        children: [
            {field:'AdlTransferring', title:'Self'}, 
            {field:'AdlTransferringSup', title:'Support' }]},
        { title: 'Eating', groupTitle: 'Eating',
        children: [
            {field:'AdlEating', title:'Self'}, 
            {field:'AdlEatingSup', title:'Support' }]},
        { title: 'Toileting', groupTitle: 'Toileting',
        children: [
            {field:'AdlToileting', title:'Self'}, 
            {field:'AdlToiletingSup', title:'Support' }]},
        { title: 'Score Variance', field:'ScoreVariance' },
        { title: 'ADL RUGs IV Score', field:'CurrentAdlRugsIV' },
        { title: 'RUGs IV End-Split', field:'AdlRugsIVDistribution' },
        { title: 'Last MDS ADL IV Score', field:'CurrentMDSRugsIV' },
        { title: 'Last MDS ADL IV End-Split', field:'MDSRugsIVDistribution' },
        { title: 'Current ADL RUGs III', field:'CurrentAdlRugsIII' },
        { title: 'Last MDS RUGs III', field:'CurrentMDSRugsIII' },
        { title: 'MDS Date', field:'MdsDt' },
        { title: '# Days Since Last MDS', field:'DayLastMDS' },
        { title: 'Payer', field:'PayerName' }

    ];

    public data = [
        {ADLdt: "2018-12-11T00:00:00",ADLdtFormatted: "12/11/2018",AdlEating: 1,AdlEatingState: "None",AdlEatingStateBgColor: null,AdlEatingStateClass: null,AdlEatingSup: 1,AdlEatingSupState: "None",AdlEatingSupStateBgColor: null,AdlEatingSupStateClass: null,AdlMdsIVComp: "ADL Less Than MDS",AdlMobility: 2,AdlMobilityState: "None",AdlMobilityStateBgColor: null,AdlMobilityStateClass: null,AdlMobilitySup: 2,AdlMobilitySupState: "None",AdlMobilitySupStateBgColor: null,AdlMobilitySupStateClass: null,AdlRugsIVDistribution: "A",AdlToileting: 2,AdlToiletingState: "None",AdlToiletingStateBgColor: null,AdlToiletingStateClass: null,AdlToiletingSup: 3,AdlToiletingSupState: "Increase",AdlToiletingSupStateBgColor: "#c5d79b",AdlToiletingSupStateClass: "k-i-arrow-up",AdlTransferring: 1,AdlTransferringState: "Decrease",AdlTransferringStateBgColor: "#fabf8f",AdlTransferringStateClass: "k-i-arrow-down",AdlTransferringSup: 2,AdlTransferringSupState: "None",AdlTransferringSupStateBgColor: null,AdlTransferringSupStateClass: null,Age: 0,CurrentAdlRugsIII: 8,CurrentAdlRugsIV: 2,CurrentMDSRugsIII: 10,CurrentMDSRugsIV: 3,DayLastMDS: 63,DaysSinceLastMDS: 0,EatingInits: null,EatingInitsExist: false,EatingSupInits: null,EatingSupInitsExist: false,EventDt: "2018-12-11T00:00:00",FacId: 4,FacilityUnitId: 21,G0110A1: 2,G0110A2: 2,G0110B1: 2,G0110B2: 2,G0110H1: 1,G0110H2: 1,G0110I1: 2,G0110I2: 2,HasChildRow: true,IllogicalAdlEatingReason: "",IllogicalAdlMobilityReason: "",IllogicalAdlToiletingReason: "",IllogicalAdlTransferringReason: "",MDSRugsIVDistribution: "A",MdsDt: "2018-10-09T00:00:00",MobilityInits: null,MobilityInitsExist: false,MobilitySupInits: null,MobilitySupInitsExist: false,OrganizationId: 4,OrganizationName: "Demo Facility D",PayerId: 61,PayerId2: 0,PayerId3: 0,PayerId4: 0,PayerId5: 0,PayerName: "Managed Medicaid",ProviderPayerId1: 0,ProviderPayerId2: 0,ProviderPayerId3: 0,ResDOB: "0001-01-01T00:00:00",ResDOBFormatted: "01/01/0001 (0)",ResId: 12427,ResMRN: "3081",ResNameF: "Daryl",ResNameL: "Andrade",Resident: "Andrade, Daryl (3081)",ResidentPhysicians: null,ResidentReferralSources: null,RiskLevel: "Moderate",RoomBed: "1214-A",ScoreVariance: -1,ShowDetail: false,ToiletingInits: null,ToiletingInitsExist: false,ToiletingSupInits: null,ToiletingSupInitsExist: false,TotalScore: 0,TransferringInits: null,TransferringInitsExist: false,TransferringSupInits: null,TransferringSupInitsExist: false,UnitName: "12th Floor"},
{ADLdt: "2018-12-11T00:00:00",ADLdtFormatted: "12/11/2018",AdlEating: 3,AdlEatingState: "Decrease",AdlEatingStateBgColor: "#fabf8f",AdlEatingStateClass: "k-i-arrow-down",AdlEatingSup: 3,AdlEatingSupState: "Increase",AdlEatingSupStateBgColor: "#c5d79b",AdlEatingSupStateClass: "k-i-arrow-up",AdlMdsIVComp: "ADL Less Than MDS",AdlMobility: 4,AdlMobilityState: "None",AdlMobilityStateBgColor: null,AdlMobilityStateClass: null,AdlMobilitySup: 3,AdlMobilitySupState: "None",AdlMobilitySupStateBgColor: null,AdlMobilitySupStateClass: null,AdlRugsIVDistribution: "C",AdlToileting: 4,AdlToiletingState: "None",AdlToiletingStateBgColor: null,AdlToiletingStateClass: null,AdlToiletingSup: 3,AdlToiletingSupState: "None",AdlToiletingSupStateBgColor: null,AdlToiletingSupStateClass: null,AdlTransferring: 4,AdlTransferringState: "None",AdlTransferringStateBgColor: null,AdlTransferringStateClass: null,AdlTransferringSup: 3,AdlTransferringSupState: "None",AdlTransferringSupStateBgColor: null,AdlTransferringSupStateClass: null,Age: 0,CurrentAdlRugsIII: 18,CurrentAdlRugsIV: 15,CurrentMDSRugsIII: 18,CurrentMDSRugsIV: 16,DayLastMDS: 17,DaysSinceLastMDS: 0,EatingInits: null,EatingInitsExist: false,EatingSupInits: null,EatingSupInitsExist: false,EventDt: "2018-12-11T00:00:00",FacId: 4,FacilityUnitId: 24,G0110A1: 4,G0110A2: 3,G0110B1: 4,G0110B2: 3,G0110H1: 4,G0110H2: 2,G0110I1: 4,G0110I2: 3,HasChildRow: true,IllogicalAdlEatingReason: "",IllogicalAdlMobilityReason: "",IllogicalAdlToiletingReason: "",IllogicalAdlTransferringReason: "",MDSRugsIVDistribution: "C",MdsDt: "2018-11-24T00:00:00",MobilityInits: null,MobilityInitsExist: false,MobilitySupInits: null,MobilitySupInitsExist: false,OrganizationId: 4,OrganizationName: "Demo Facility D",PayerId: 26,PayerId2: 0,PayerId3: 0,PayerId4: 0,PayerId5: 0,PayerName: "Medicaid",ProviderPayerId1: 0,ProviderPayerId2: 0,ProviderPayerId3: 0,ResDOB: "0001-01-01T00:00:00",ResDOBFormatted: "01/01/0001 (0)",ResId: 18496,ResMRN: "2416",ResNameF: "Zenobia",ResNameL: "Bent",Resident: "Bent, Zenobia (2416)",ResidentPhysicians: null,ResidentReferralSources: null,RiskLevel: "Low",RoomBed: "1003-B",ScoreVariance: -1,ShowDetail: false,ToiletingInits: null,ToiletingInitsExist: false,ToiletingSupInits: null,ToiletingSupInitsExist: false,TotalScore: 0,TransferringInits: null,TransferringInitsExist: false,TransferringSupInits: null,TransferringSupInitsExist: false,UnitName: "10th Floor"},
{ADLdt: "2018-12-11T00:00:00",ADLdtFormatted: "12/11/2018",AdlEating: 2,AdlEatingState: "Decrease",AdlEatingStateBgColor: "#fabf8f",AdlEatingStateClass: "k-i-arrow-down",AdlEatingSup: 2,AdlEatingSupState: "None",AdlEatingSupStateBgColor: null,AdlEatingSupStateClass: null,AdlMdsIVComp: "ADL Less Than MDS",AdlMobility: 3,AdlMobilityState: "None",AdlMobilityStateBgColor: null,AdlMobilityStateClass: null,AdlMobilitySup: 2,AdlMobilitySupState: "None",AdlMobilitySupStateBgColor: null,AdlMobilitySupStateClass: null,AdlRugsIVDistribution: "B",AdlToileting: 3,AdlToiletingState: "None",AdlToiletingStateBgColor: null,AdlToiletingStateClass: null,AdlToiletingSup: 3,AdlToiletingSupState: "None",AdlToiletingSupStateBgColor: null,AdlToiletingSupStateClass: null,AdlTransferring: 3,AdlTransferringState: "None",AdlTransferringStateBgColor: null,AdlTransferringStateClass: null,AdlTransferringSup: 2,AdlTransferringSupState: "None",AdlTransferringSupStateBgColor: null,AdlTransferringSupStateClass: null,Age: 0,CurrentAdlRugsIII: 15,CurrentAdlRugsIV: 10,CurrentMDSRugsIII: 16,CurrentMDSRugsIV: 11,DayLastMDS: 24,DaysSinceLastMDS: 0,EatingInits: null,EatingInitsExist: false,EatingSupInits: null,EatingSupInitsExist: false,EventDt: "2018-12-11T00:00:00",FacId: 4,FacilityUnitId: 30,G0110A1: 3,G0110A2: 2,G0110B1: 3,G0110B2: 2,G0110H1: 3,G0110H2: 2,G0110I1: 3,G0110I2: 3,HasChildRow: true,IllogicalAdlEatingReason: "",IllogicalAdlMobilityReason: "",IllogicalAdlToiletingReason: "",IllogicalAdlTransferringReason: "",MDSRugsIVDistribution: "C",MdsDt: "2018-11-17T00:00:00",MobilityInits: null,MobilityInitsExist: false,MobilitySupInits: null,MobilitySupInitsExist: false,OrganizationId: 4,OrganizationName: "Demo Facility D",PayerId: 61,PayerId2: 0,PayerId3: 0,PayerId4: 0,PayerId5: 0,PayerName: "Managed Medicaid",ProviderPayerId1: 0,ProviderPayerId2: 0,ProviderPayerId3: 0,ResDOB: "0001-01-01T00:00:00",ResDOBFormatted: "01/01/0001 (0)",ResId: 12646,ResMRN: "3153",ResNameF: "Hilde",ResNameL: "Bicket",Resident: "Bicket, Hilde (3153)",ResidentPhysicians: null,ResidentReferralSources: null,RiskLevel: "Low",RoomBed: "828-A",ScoreVariance: -1,ShowDetail: false,ToiletingInits: null,ToiletingInitsExist: false,ToiletingSupInits: null,ToiletingSupInitsExist: false,TotalScore: 0,TransferringInits: null,TransferringInitsExist: false,TransferringSupInits: null,TransferringSupInitsExist: false,UnitName: "8th Floor"},
{ADLdt: "2018-12-11T00:00:00",ADLdtFormatted: "12/11/2018",AdlEating: 2,AdlEatingState: "Decrease",AdlEatingStateBgColor: "#fabf8f",AdlEatingStateClass: "k-i-arrow-down",AdlEatingSup: 3,AdlEatingSupState: "Increase",AdlEatingSupStateBgColor: "#c5d79b",AdlEatingSupStateClass: "k-i-arrow-up",AdlMdsIVComp: "ADL Less Than MDS",AdlMobility: 1,AdlMobilityState: "None",AdlMobilityStateBgColor: null,AdlMobilityStateClass: null,AdlMobilitySup: 2,AdlMobilitySupState: "None",AdlMobilitySupStateBgColor: null,AdlMobilitySupStateClass: null,AdlRugsIVDistribution: "A",AdlToileting: 2,AdlToiletingState: "None",AdlToiletingStateBgColor: null,AdlToiletingStateClass: null,AdlToiletingSup: 2,AdlToiletingSupState: "None",AdlToiletingSupStateBgColor: null,AdlToiletingSupStateClass: null,AdlTransferring: 1,AdlTransferringState: "None",AdlTransferringStateBgColor: null,AdlTransferringStateClass: null,AdlTransferringSup: 2,AdlTransferringSupState: "None",AdlTransferringSupStateBgColor: null,AdlTransferringSupStateClass: null,Age: 0,CurrentAdlRugsIII: 7,CurrentAdlRugsIV: 3,CurrentMDSRugsIII: 8,CurrentMDSRugsIV: 4,DayLastMDS: 77,DaysSinceLastMDS: 0,EatingInits: null,EatingInitsExist: false,EatingSupInits: null,EatingSupInitsExist: false,EventDt: "2018-12-11T00:00:00",FacId: 4,FacilityUnitId: 30,G0110A1: 1,G0110A2: 2,G0110B1: 1,G0110B2: 2,G0110H1: 3,G0110H2: 2,G0110I1: 2,G0110I2: 2,HasChildRow: true,IllogicalAdlEatingReason: "",IllogicalAdlMobilityReason: "",IllogicalAdlToiletingReason: "",IllogicalAdlTransferringReason: "",MDSRugsIVDistribution: "A",MdsDt: "2018-09-25T00:00:00",MobilityInits: null,MobilityInitsExist: false,MobilitySupInits: null,MobilitySupInitsExist: false,OrganizationId: 4,OrganizationName: "Demo Facility D",PayerId: 26,PayerId2: 0,PayerId3: 0,PayerId4: 0,PayerId5: 0,PayerName: "Medicaid",ProviderPayerId1: 0,ProviderPayerId2: 0,ProviderPayerId3: 0,ResDOB: "0001-01-01T00:00:00",ResDOBFormatted: "01/01/0001 (0)",ResId: 7844,ResMRN: "2649",ResNameF: "Tonia",ResNameL: "Bills",Resident: "Bills, Tonia (2649)",ResidentPhysicians: null,ResidentReferralSources: null,RiskLevel: "Low",RoomBed: "810-A",ScoreVariance: -1,ShowDetail: false,ToiletingInits: null,ToiletingInitsExist: false,ToiletingSupInits: null,ToiletingSupInitsExist: false,TotalScore: 0,TransferringInits: null,TransferringInitsExist: false,TransferringSupInits: null,TransferringSupInitsExist: false,UnitName: "8th Floor"},
{ADLdt: "2018-12-11T00:00:00",ADLdtFormatted: "12/11/2018",AdlEating: 1,AdlEatingState: "None",AdlEatingStateBgColor: null,AdlEatingStateClass: null,AdlEatingSup: 1,AdlEatingSupState: "None",AdlEatingSupStateBgColor: null,AdlEatingSupStateClass: null,AdlMdsIVComp: "ADL Less Than MDS",AdlMobility: 1,AdlMobilityState: "Decrease",AdlMobilityStateBgColor: "#fabf8f",AdlMobilityStateClass: "k-i-arrow-down",AdlMobilitySup: 1,AdlMobilitySupState: "Decrease",AdlMobilitySupStateBgColor: "#fabf8f",AdlMobilitySupStateClass: "k-i-arrow-down",AdlRugsIVDistribution: "A",AdlToileting: 3,AdlToiletingState: "None",AdlToiletingStateBgColor: null,AdlToiletingStateClass: null,AdlToiletingSup: 2,AdlToiletingSupState: "None",AdlToiletingSupStateBgColor: null,AdlToiletingSupStateClass: null,AdlTransferring: 3,AdlTransferringState: "None",AdlTransferringStateBgColor: null,AdlTransferringStateClass: null,AdlTransferringSup: 2,AdlTransferringSupState: "None",AdlTransferringSupStateBgColor: null,AdlTransferringSupStateClass: null,Age: 0,CurrentAdlRugsIII: 10,CurrentAdlRugsIV: 4,CurrentMDSRugsIII: 12,CurrentMDSRugsIV: 5,DayLastMDS: 85,DaysSinceLastMDS: 0,EatingInits: null,EatingInitsExist: false,EatingSupInits: null,EatingSupInitsExist: false,EventDt: "2018-12-11T00:00:00",FacId: 4,FacilityUnitId: 20,G0110A1: 2,G0110A2: 2,G0110B1: 3,G0110B2: 2,G0110H1: 1,G0110H2: 1,G0110I1: 3,G0110I2: 2,HasChildRow: true,IllogicalAdlEatingReason: "",IllogicalAdlMobilityReason: "",IllogicalAdlToiletingReason: "",IllogicalAdlTransferringReason: "",MDSRugsIVDistribution: "A",MdsDt: "2018-09-17T00:00:00",MobilityInits: null,MobilityInitsExist: false,MobilitySupInits: null,MobilitySupInitsExist: false,OrganizationId: 4,OrganizationName: "Demo Facility D",PayerId: 26,PayerId2: 0,PayerId3: 0,PayerId4: 0,PayerId5: 0,PayerName: "Medicaid",ProviderPayerId1: 0,ProviderPayerId2: 0,ProviderPayerId3: 0,ResDOB: "0001-01-01T00:00:00",ResDOBFormatted: "01/01/0001 (0)",ResId: 2074,ResMRN: "1547",ResNameF: "Lilly",ResNameL: "Carty",Resident: "Carty, Lilly (1547)",ResidentPhysicians: null,ResidentReferralSources: null,RiskLevel: "Low",RoomBed: "920-A",ScoreVariance: -1,ShowDetail: false,ToiletingInits: null,ToiletingInitsExist: false,ToiletingSupInits: null,ToiletingSupInitsExist: false,TotalScore: 0,TransferringInits: null,TransferringInitsExist: false,TransferringSupInits: null,TransferringSupInitsExist: false,UnitName: "9th Floor"},
{ADLdt: "2018-12-11T00:00:00",ADLdtFormatted: "12/11/2018",AdlEating: 4,AdlEatingState: "Increase",AdlEatingStateBgColor: "#c5d79b",AdlEatingStateClass: "k-i-arrow-up",AdlEatingSup: 3,AdlEatingSupState: "Increase",AdlEatingSupStateBgColor: "#c5d79b",AdlEatingSupStateClass: "k-i-arrow-up",AdlMdsIVComp: "ADL Less Than MDS",AdlMobility: 3,AdlMobilityState: "None",AdlMobilityStateBgColor: null,AdlMobilityStateClass: null,AdlMobilitySup: 2,AdlMobilitySupState: "Decrease",AdlMobilitySupStateBgColor: "#fabf8f",AdlMobilitySupStateClass: "k-i-arrow-down",AdlRugsIVDistribution: "C",AdlToileting: 4,AdlToiletingState: "Increase",AdlToiletingStateBgColor: "#c5d79b",AdlToiletingStateClass: "k-i-arrow-up",AdlToiletingSup: 3,AdlToiletingSupState: "None",AdlToiletingSupStateBgColor: null,AdlToiletingSupStateClass: null,AdlTransferring: 4,AdlTransferringState: "Increase",AdlTransferringStateBgColor: "#c5d79b",AdlTransferringStateClass: "k-i-arrow-up",AdlTransferringSup: 3,AdlTransferringSupState: "None",AdlTransferringSupStateBgColor: null,AdlTransferringSupStateClass: null,Age: 0,CurrentAdlRugsIII: 17,CurrentAdlRugsIV: 14,CurrentMDSRugsIII: 18,CurrentMDSRugsIV: 15,DayLastMDS: 36,DaysSinceLastMDS: 0,EatingInits: null,EatingInitsExist: false,EatingSupInits: null,EatingSupInitsExist: false,EventDt: "2018-12-11T00:00:00",FacId: 4,FacilityUnitId: 29,G0110A1: 3,G0110A2: 3,G0110B1: 3,G0110B2: 3,G0110H1: 3,G0110H2: 2,G0110I1: 3,G0110I2: 3,HasChildRow: true,IllogicalAdlEatingReason: "",IllogicalAdlMobilityReason: "",IllogicalAdlToiletingReason: "",IllogicalAdlTransferringReason: "",MDSRugsIVDistribution: "C",MdsDt: "2018-11-05T00:00:00",MobilityInits: null,MobilityInitsExist: false,MobilitySupInits: null,MobilitySupInitsExist: false,OrganizationId: 4,OrganizationName: "Demo Facility D",PayerId: 26,PayerId2: 0,PayerId3: 0,PayerId4: 0,PayerId5: 0,PayerName: "Medicaid",ProviderPayerId1: 0,ProviderPayerId2: 0,ProviderPayerId3: 0,ResDOB: "0001-01-01T00:00:00",ResDOBFormatted: "01/01/0001 (0)",ResId: 11643,ResMRN: "20040",ResNameF: "Benita",ResNameL: "Chevarie",Resident: "Chevarie, Benita (20040)",ResidentPhysicians: null,ResidentReferralSources: null,RiskLevel: "Low",RoomBed: "1323-B",ScoreVariance: -1,ShowDetail: false,ToiletingInits: null,ToiletingInitsExist: false,ToiletingSupInits: null,ToiletingSupInitsExist: false,TotalScore: 0,TransferringInits: null,TransferringInitsExist: false,TransferringSupInits: null,TransferringSupInitsExist: false,UnitName: "13th Floor"},
{ADLdt: "2018-12-11T00:00:00",ADLdtFormatted: "12/11/2018",AdlEating: 1,AdlEatingState: "Decrease",AdlEatingStateBgColor: "#fabf8f",AdlEatingStateClass: "k-i-arrow-down",AdlEatingSup: 3,AdlEatingSupState: "Increase",AdlEatingSupStateBgColor: "#c5d79b",AdlEatingSupStateClass: "k-i-arrow-up",AdlMdsIVComp: "ADL Less Than MDS",AdlMobility: 3,AdlMobilityState: "None",AdlMobilityStateBgColor: null,AdlMobilityStateClass: null,AdlMobilitySup: 3,AdlMobilitySupState: "None",AdlMobilitySupStateBgColor: null,AdlMobilitySupStateClass: null,AdlRugsIVDistribution: "C",AdlToileting: 3,AdlToiletingState: "None",AdlToiletingStateBgColor: null,AdlToiletingStateClass: null,AdlToiletingSup: 3,AdlToiletingSupState: "None",AdlToiletingSupStateBgColor: null,AdlToiletingSupStateClass: null,AdlTransferring: 3,AdlTransferringState: "None",AdlTransferringStateBgColor: null,AdlTransferringStateClass: null,AdlTransferringSup: 3,AdlTransferringSupState: "None",AdlTransferringSupStateBgColor: null,AdlTransferringSupStateClass: null,Age: 0,CurrentAdlRugsIII: 16,CurrentAdlRugsIV: 14,CurrentMDSRugsIII: 18,CurrentMDSRugsIV: 15,DayLastMDS: 85,DaysSinceLastMDS: 0,EatingInits: null,EatingInitsExist: false,EatingSupInits: null,EatingSupInitsExist: false,EventDt: "2018-12-11T00:00:00",FacId: 4,FacilityUnitId: 23,G0110A1: 3,G0110A2: 3,G0110B1: 3,G0110B2: 3,G0110H1: 3,G0110H2: 2,G0110I1: 3,G0110I2: 3,HasChildRow: true,IllogicalAdlEatingReason: "",IllogicalAdlMobilityReason: "",IllogicalAdlToiletingReason: "",IllogicalAdlTransferringReason: "",MDSRugsIVDistribution: "C",MdsDt: "2018-09-17T00:00:00",MobilityInits: null,MobilityInitsExist: false,MobilitySupInits: null,MobilitySupInitsExist: false,OrganizationId: 4,OrganizationName: "Demo Facility D",PayerId: 74,PayerId2: 0,PayerId3: 0,PayerId4: 0,PayerId5: 0,PayerName: "Medicare A",ProviderPayerId1: 0,ProviderPayerId2: 0,ProviderPayerId3: 0,ResDOB: "0001-01-01T00:00:00",ResDOBFormatted: "01/01/0001 (0)",ResId: 16312,ResMRN: "3212",ResNameF: "Percy",ResNameL: "Deshner",Resident: "Deshner, Percy (3212)",ResidentPhysicians: null,ResidentReferralSources: null,RiskLevel: "Moderate",RoomBed: "610-A",ScoreVariance: -1,ShowDetail: false,ToiletingInits: null,ToiletingInitsExist: false,ToiletingSupInits: null,ToiletingSupInitsExist: false,TotalScore: 0,TransferringInits: null,TransferringInitsExist: false,TransferringSupInits: null,TransferringSupInitsExist: false,UnitName: "6th Floor"},
{ADLdt: "2018-12-11T00:00:00",ADLdtFormatted: "12/11/2018",AdlEating: 1,AdlEatingState: "Decrease",AdlEatingStateBgColor: "#fabf8f",AdlEatingStateClass: "k-i-arrow-down",AdlEatingSup: 2,AdlEatingSupState: "None",AdlEatingSupStateBgColor: null,AdlEatingSupStateClass: null,AdlMdsIVComp: "ADL Less Than MDS",AdlMobility: 2,AdlMobilityState: "None",AdlMobilityStateBgColor: null,AdlMobilityStateClass: null,AdlMobilitySup: 2,AdlMobilitySupState: "None",AdlMobilitySupStateBgColor: null,AdlMobilitySupStateClass: null,AdlRugsIVDistribution: "A",AdlToileting: 1,AdlToiletingState: "None",AdlToiletingStateBgColor: null,AdlToiletingStateClass: null,AdlToiletingSup: 1,AdlToiletingSupState: "None",AdlToiletingSupStateBgColor: null,AdlToiletingSupStateClass: null,AdlTransferring: 2,AdlTransferringState: "None",AdlTransferringStateBgColor: null,AdlTransferringStateClass: null,AdlTransferringSup: 2,AdlTransferringSupState: "None",AdlTransferringSupStateBgColor: null,AdlTransferringSupStateClass: null,Age: 0,CurrentAdlRugsIII: 8,CurrentAdlRugsIV: 4,CurrentMDSRugsIII: 10,CurrentMDSRugsIV: 5,DayLastMDS: 72,DaysSinceLastMDS: 0,EatingInits: null,EatingInitsExist: false,EatingSupInits: null,EatingSupInitsExist: false,EventDt: "2018-12-11T00:00:00",FacId: 4,FacilityUnitId: 23,G0110A1: 2,G0110A2: 2,G0110B1: 2,G0110B2: 2,G0110H1: 3,G0110H2: 2,G0110I1: 1,G0110I2: 1,HasChildRow: true,IllogicalAdlEatingReason: "",IllogicalAdlMobilityReason: "",IllogicalAdlToiletingReason: "",IllogicalAdlTransferringReason: "",MDSRugsIVDistribution: "A",MdsDt: "2018-09-30T00:00:00",MobilityInits: null,MobilityInitsExist: false,MobilitySupInits: null,MobilitySupInitsExist: false,OrganizationId: 4,OrganizationName: "Demo Facility D",PayerId: 61,PayerId2: 0,PayerId3: 0,PayerId4: 0,PayerId5: 0,PayerName: "Managed Medicaid",ProviderPayerId1: 0,ProviderPayerId2: 0,ProviderPayerId3: 0,ResDOB: "0001-01-01T00:00:00",ResDOBFormatted: "01/01/0001 (0)",ResId: 7689,ResMRN: "2616",ResNameF: "Janna",ResNameL: "Dyson",Resident: "Dyson, Janna (2616)",ResidentPhysicians: null,ResidentReferralSources: null,RiskLevel: "Low",RoomBed: "611-B",ScoreVariance: -1,ShowDetail: false,ToiletingInits: null,ToiletingInitsExist: false,ToiletingSupInits: null,ToiletingSupInitsExist: false,TotalScore: 0,TransferringInits: null,TransferringInitsExist: false,TransferringSupInits: null,TransferringSupInitsExist: false,UnitName: "6th Floor"},
{ADLdt: "2018-12-11T00:00:00",ADLdtFormatted: "12/11/2018",AdlEating: 3,AdlEatingState: "Decrease",AdlEatingStateBgColor: "#fabf8f",AdlEatingStateClass: "k-i-arrow-down",AdlEatingSup: 2,AdlEatingSupState: "None",AdlEatingSupStateBgColor: null,AdlEatingSupStateClass: null,AdlMdsIVComp: "ADL Less Than MDS",AdlMobility: 3,AdlMobilityState: "None",AdlMobilityStateBgColor: null,AdlMobilityStateClass: null,AdlMobilitySup: 3,AdlMobilitySupState: "None",AdlMobilitySupStateBgColor: null,AdlMobilitySupStateClass: null,AdlRugsIVDistribution: "C",AdlToileting: 3,AdlToiletingState: "None",AdlToiletingStateBgColor: null,AdlToiletingStateClass: null,AdlToiletingSup: 3,AdlToiletingSupState: "None",AdlToiletingSupStateBgColor: null,AdlToiletingSupStateClass: null,AdlTransferring: 3,AdlTransferringState: "None",AdlTransferringStateBgColor: null,AdlTransferringStateClass: null,AdlTransferringSup: 3,AdlTransferringSupState: "None",AdlTransferringSupStateBgColor: null,AdlTransferringSupStateClass: null,Age: 0,CurrentAdlRugsIII: 18,CurrentAdlRugsIV: 15,CurrentMDSRugsIII: 18,CurrentMDSRugsIV: 16,DayLastMDS: 15,DaysSinceLastMDS: 0,EatingInits: null,EatingInitsExist: false,EatingSupInits: null,EatingSupInitsExist: false,EventDt: "2018-12-11T00:00:00",FacId: 4,FacilityUnitId: 28,G0110A1: 3,G0110A2: 3,G0110B1: 3,G0110B2: 3,G0110H1: 4,G0110H2: 2,G0110I1: 3,G0110I2: 3,HasChildRow: true,IllogicalAdlEatingReason: "",IllogicalAdlMobilityReason: "",IllogicalAdlToiletingReason: "",IllogicalAdlTransferringReason: "",MDSRugsIVDistribution: "C",MdsDt: "2018-11-26T00:00:00",MobilityInits: null,MobilityInitsExist: false,MobilitySupInits: null,MobilitySupInitsExist: false,OrganizationId: 4,OrganizationName: "Demo Facility D",PayerId: 74,PayerId2: 0,PayerId3: 0,PayerId4: 0,PayerId5: 0,PayerName: "Medicare A",ProviderPayerId1: 0,ProviderPayerId2: 0,ProviderPayerId3: 0,ResDOB: "0001-01-01T00:00:00",ResDOBFormatted: "01/01/0001 (0)",ResId: 8133,ResMRN: "3518",ResNameF: "Sally",ResNameL: "Eibell",Resident: "Eibell, Sally (3518)",ResidentPhysicians: null,ResidentReferralSources: null,RiskLevel: "Low",RoomBed: "527-A",ScoreVariance: -1,ShowDetail: false,ToiletingInits: null,ToiletingInitsExist: false,ToiletingSupInits: null,ToiletingSupInitsExist: false,TotalScore: 0,TransferringInits: null,TransferringInitsExist: false,TransferringSupInits: null,TransferringSupInitsExist: false,UnitName: "5th Floor"},
{ADLdt: "2018-12-11T00:00:00",ADLdtFormatted: "12/11/2018",AdlEating: 2,AdlEatingState: "None",AdlEatingStateBgColor: null,AdlEatingStateClass: null,AdlEatingSup: 2,AdlEatingSupState: "None",AdlEatingSupStateBgColor: null,AdlEatingSupStateClass: null,AdlMdsIVComp: "ADL Less Than MDS",AdlMobility: 1,AdlMobilityState: "None",AdlMobilityStateBgColor: null,AdlMobilityStateClass: null,AdlMobilitySup: 2,AdlMobilitySupState: "None",AdlMobilitySupStateBgColor: null,AdlMobilitySupStateClass: null,AdlRugsIVDistribution: "A",AdlToileting: 3,AdlToiletingState: "None",AdlToiletingStateBgColor: null,AdlToiletingStateClass: null,AdlToiletingSup: 2,AdlToiletingSupState: "None",AdlToiletingSupStateBgColor: null,AdlToiletingSupStateClass: null,AdlTransferring: 1,AdlTransferringState: "Decrease",AdlTransferringStateBgColor: "#fabf8f",AdlTransferringStateClass: "k-i-arrow-down",AdlTransferringSup: 2,AdlTransferringSupState: "None",AdlTransferringSupStateBgColor: null,AdlTransferringSupStateClass: null,Age: 0,CurrentAdlRugsIII: 8,CurrentAdlRugsIV: 4,CurrentMDSRugsIII: 10,CurrentMDSRugsIV: 5,DayLastMDS: 41,DaysSinceLastMDS: 0,EatingInits: null,EatingInitsExist: false,EatingSupInits: null,EatingSupInitsExist: false,EventDt: "2018-12-11T00:00:00",FacId: 4,FacilityUnitId: 30,G0110A1: 1,G0110A2: 2,G0110B1: 2,G0110B2: 2,G0110H1: 2,G0110H2: 2,G0110I1: 3,G0110I2: 2,HasChildRow: true,IllogicalAdlEatingReason: "",IllogicalAdlMobilityReason: "",IllogicalAdlToiletingReason: "",IllogicalAdlTransferringReason: "",MDSRugsIVDistribution: "A",MdsDt: "2018-10-31T00:00:00",MobilityInits: null,MobilityInitsExist: false,MobilitySupInits: null,MobilitySupInitsExist: false,OrganizationId: 4,OrganizationName: "Demo Facility D",PayerId: 26,PayerId2: 0,PayerId3: 0,PayerId4: 0,PayerId5: 0,PayerName: "Medicaid",ProviderPayerId1: 0,ProviderPayerId2: 0,ProviderPayerId3: 0,ResDOB: "0001-01-01T00:00:00",ResDOBFormatted: "01/01/0001 (0)",ResId: 28313,ResMRN: "1661",ResNameF: "Jayme",ResNameL: "Kayat",Resident: "Kayat, Jayme (1661)",ResidentPhysicians: null,ResidentReferralSources: null,RiskLevel: "Low",RoomBed: "802-A",ScoreVariance: -1,ShowDetail: false,ToiletingInits: null,ToiletingInitsExist: false,ToiletingSupInits: null,ToiletingSupInitsExist: false,TotalScore: 0,TransferringInits: null,TransferringInitsExist: false,TransferringSupInits: null,TransferringSupInitsExist: false,UnitName: "8th Floor"},
{ADLdt: "2018-12-11T00:00:00",ADLdtFormatted: "12/11/2018",AdlEating: 1,AdlEatingState: "None",AdlEatingStateBgColor: null,AdlEatingStateClass: null,AdlEatingSup: 1,AdlEatingSupState: "Decrease",AdlEatingSupStateBgColor: "#fabf8f",AdlEatingSupStateClass: "k-i-arrow-down",AdlMdsIVComp: "ADL Less Than MDS",AdlMobility: 3,AdlMobilityState: "None",AdlMobilityStateBgColor: null,AdlMobilityStateClass: null,AdlMobilitySup: 3,AdlMobilitySupState: "None",AdlMobilitySupStateBgColor: null,AdlMobilitySupStateClass: null,AdlRugsIVDistribution: "C",AdlToileting: 4,AdlToiletingState: "None",AdlToiletingStateBgColor: null,AdlToiletingStateClass: null,AdlToiletingSup: 3,AdlToiletingSupState: "Increase",AdlToiletingSupStateBgColor: "#c5d79b",AdlToiletingSupStateClass: "k-i-arrow-up",AdlTransferring: 3,AdlTransferringState: "None",AdlTransferringStateBgColor: null,AdlTransferringStateClass: null,AdlTransferringSup: 3,AdlTransferringSupState: "None",AdlTransferringSupStateBgColor: null,AdlTransferringSupStateClass: null,Age: 0,CurrentAdlRugsIII: 16,CurrentAdlRugsIV: 12,CurrentMDSRugsIII: 15,CurrentMDSRugsIV: 13,DayLastMDS: 11,DaysSinceLastMDS: 0,EatingInits: null,EatingInitsExist: false,EatingSupInits: null,EatingSupInitsExist: false,EventDt: "2018-12-11T00:00:00",FacId: 4,FacilityUnitId: 21,G0110A1: 3,G0110A2: 3,G0110B1: 3,G0110B2: 3,G0110H1: 1,G0110H2: 2,G0110I1: 4,G0110I2: 2,HasChildRow: true,IllogicalAdlEatingReason: "",IllogicalAdlMobilityReason: "",IllogicalAdlToiletingReason: "",IllogicalAdlTransferringReason: "",MDSRugsIVDistribution: "C",MdsDt: "2018-11-30T00:00:00",MobilityInits: null,MobilityInitsExist: false,MobilitySupInits: null,MobilitySupInitsExist: false,OrganizationId: 4,OrganizationName: "Demo Facility D",PayerId: 61,PayerId2: 0,PayerId3: 0,PayerId4: 0,PayerId5: 0,PayerName: "Managed Medicaid",ProviderPayerId1: 0,ProviderPayerId2: 0,ProviderPayerId3: 0,ResDOB: "0001-01-01T00:00:00",ResDOBFormatted: "01/01/0001 (0)",ResId: 27290,ResMRN: "2910",ResNameF: "Una",ResNameL: "Kinneman",Resident: "Kinneman, Una (2910)",ResidentPhysicians: null,ResidentReferralSources: null,RiskLevel: "Moderate",RoomBed: "1203-B",ScoreVariance: -1,ShowDetail: false,ToiletingInits: null,ToiletingInitsExist: false,ToiletingSupInits: null,ToiletingSupInitsExist: false,TotalScore: 0,TransferringInits: null,TransferringInitsExist: false,TransferringSupInits: null,TransferringSupInitsExist: false,UnitName: "12th Floor"},
{ADLdt: "2018-12-11T00:00:00",ADLdtFormatted: "12/11/2018",AdlEating: 2,AdlEatingState: "Increase",AdlEatingStateBgColor: "#c5d79b",AdlEatingStateClass: "k-i-arrow-up",AdlEatingSup: 2,AdlEatingSupState: "None",AdlEatingSupStateBgColor: null,AdlEatingSupStateClass: null,AdlMdsIVComp: "ADL Less Than MDS",AdlMobility: 1,AdlMobilityState: "None",AdlMobilityStateBgColor: null,AdlMobilityStateClass: null,AdlMobilitySup: 2,AdlMobilitySupState: "Increase",AdlMobilitySupStateBgColor: "#c5d79b",AdlMobilitySupStateClass: "k-i-arrow-up",AdlRugsIVDistribution: "A",AdlToileting: 1,AdlToiletingState: "Decrease",AdlToiletingStateBgColor: "#fabf8f",AdlToiletingStateClass: "k-i-arrow-down",AdlToiletingSup: 2,AdlToiletingSupState: "None",AdlToiletingSupStateBgColor: null,AdlToiletingSupStateClass: null,AdlTransferring: 1,AdlTransferringState: "None",AdlTransferringStateBgColor: null,AdlTransferringStateClass: null,AdlTransferringSup: 2,AdlTransferringSupState: "Increase",AdlTransferringSupStateBgColor: "#c5d79b",AdlTransferringSupStateClass: "k-i-arrow-up",Age: 0,CurrentAdlRugsIII: 5,CurrentAdlRugsIV: 2,CurrentMDSRugsIII: 6,CurrentMDSRugsIV: 3,DayLastMDS: 56,DaysSinceLastMDS: 0,EatingInits: null,EatingInitsExist: false,EatingSupInits: null,EatingSupInitsExist: false,EventDt: "2018-12-11T00:00:00",FacId: 4,FacilityUnitId: 30,G0110A1: 1,G0110A2: 1,G0110B1: 1,G0110B2: 1,G0110H1: 1,G0110H2: 2,G0110I1: 2,G0110I2: 2,HasChildRow: true,IllogicalAdlEatingReason: "",IllogicalAdlMobilityReason: "",IllogicalAdlToiletingReason: "",IllogicalAdlTransferringReason: "",MDSRugsIVDistribution: "A",MdsDt: "2018-10-16T00:00:00",MobilityInits: null,MobilityInitsExist: false,MobilitySupInits: null,MobilitySupInitsExist: false,OrganizationId: 4,OrganizationName: "Demo Facility D",PayerId: 26,PayerId2: 0,PayerId3: 0,PayerId4: 0,PayerId5: 0,PayerName: "Medicaid",ProviderPayerId1: 0,ProviderPayerId2: 0,ProviderPayerId3: 0,ResDOB: "0001-01-01T00:00:00",ResDOBFormatted: "01/01/0001 (0)",ResId: 20715,ResMRN: "1524",ResNameF: "Emerita",ResNameL: "Lietzke",Resident: "Lietzke, Emerita (1524)",ResidentPhysicians: null,ResidentReferralSources: null,RiskLevel: "Low",RoomBed: "803-A",ScoreVariance: -1,ShowDetail: false,ToiletingInits: null,ToiletingInitsExist: false,ToiletingSupInits: null,ToiletingSupInitsExist: false,TotalScore: 0,TransferringInits: null,TransferringInitsExist: false,TransferringSupInits: null,TransferringSupInitsExist: false,UnitName: "8th Floor"}
    ];

    public residentScoreIndicatorClick(event,data){
        alert(data.Resident + " Clicked");
    }

    public sortChange(sort: SortDescriptor[]): void {
        this.sort = sort;
        this.loadProducts();
    }

    private loadProducts(): void {
        this.gridData = {
            data: orderBy(this.data.slice(this.skip, this.skip + this.pageSize), this.sort),
            total: this.data.length
        };
    }

    public sort: SortDescriptor[] = [{
        field: 'ProductName',
        dir: 'desc'
    }];

    public pageChange(event: PageChangeEvent): void {
        this.skip = event.skip;
        this.loadProducts();
    }   
    
    public getToolTip(condition1, condition1Value, condition2) {
        var returnValue = '';

        if (this.isShowTooltip && condition1) {
            returnValue = condition1Value;
        }
        else if (condition2!=='None') {
            returnValue = condition2 + ' since last MDS';
        }

        return returnValue;
    };
}

import { Pipe,PipeTransform} from '@angular/core';

@Pipe({
    name: 'searchFilter'
})
export class SearchFilter implements PipeTransform {
    transform(items: GridDataResult, searchString: any): any {

        return items.data.filter(item =>{
            for (let key in item ) {
                if((''+item[key]).toLocaleLowerCase().includes(searchString.toLocaleLowerCase())){
                   return true;
                }
              }
           return false;
        });
    }
}
